;; -*- mode: eask; lexical-binding: t -*-

(package "faster-whichkey"
         "1.0.0"
         "Makes startup with whichkey faster")

(website-url "https://github.com/jgrey4296/faster-whichkey")
(keywords )

(package-descriptor "faster-whichkey-pkg.el")
(files "faster-whichkey.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "30.2")
(depends-on "general")
(depends-on "which-key")
